apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test
  namespace: kong
spec:
  targetNamespace: kong
  interval: 10m
  chart:
    spec:
      # https://github.com/Kong/charts/tree/kong-1.15.2/charts/kong
      chart: kong
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
