apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: kong
spec:
  interval: 10m
  chart:
    spec:
      # https://github.com/Kong/charts/tree/kong-1.15.2/charts/kong
      chart: kong
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: kong
        namespace: flux-system
  interval: 1h0m0s
    install:
      remediation:
        retries: 3
  values:
    installCRDs: false
    ingressController:
      installCRDs: false
